title: 오픈소스 가이드
description: 오픈소스 제작자를 위한 커뮤니티 가이드

# See: docs/translations.md
locale: ko-KR
translations:
  - locale: en-US
    name: English (US)
    repository: github/open-source-guide
  - locale: ko-KR
    name: Korean (KR)
    repository: 2korean/open-source-guide

exclude:
  - bin
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - docs
  - Gemfile*
  - node_modules
  - package.json
  - Rakefile
  - README.md
  - script
  - test
  - vendor
  - node_modules

permalink: /:path/

collections:
  articles:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/cards/default.png
  - scope:
      path: ""
      type: articles
    values:
      layout: article

gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

sass:
  style: :compressed
  sass_dir: assets/css/
  load_paths:
    - node_modules
    - node_modules/**/*/node_modules

branch: gh-pages

github:
  repository_nwo: github/open-source-guide

twitter:
  username: github

facebook:
  publisher: https://www.facebook.com/GitHub/
